import type { Scenario } from '../engine/demo/types';

export const kqyy: Scenario = {
  id: 'kqyy',
  meta: {
    项目名: '北京口腔医院 2026 年度医用设备相关计量检测项目',
    采购人: '北京口腔医院',
    采购方式: '公开遴选',
    评审办法: '综合评分法 (100 分)',
    限价: 270000,
    报价: 269820,
    报价利用率: '99.93%',
    保证金: 5400,
    服务周期: '1 年',
  },
  strategy: {
    method: 'composite',
    基调: '综合评分法 → 目标是「堆满技术分」，价格权重低，支持顶格高价报价',
    报价基调: '顶格高价报价（利用率 99.93%，争取满分技术池下最大化收益）',
  },
  volumes: [
    {
      id: 'vol.1',
      名称: '投标文件 (响应分册)',
      单独密封: false,
      chapters: [
        { id: 'chap.1', 标题: '第一章 营业执照与 CMA/CNAS 资质', 类型: '填空区' },
        { id: 'chap.2', 标题: '第二章 资格声明书', 类型: '填空区' },
        { id: 'chap.3', 标题: '第三章 承诺函与承诺书', 类型: '填空区' },
        { id: 'chap.5', 标题: '第五章 开标一览表', 类型: '填空区' },
        { id: 'chap.6', 标题: '第六章 分项报价表', 类型: '填空区' },
        { id: 'chap.7', 标题: '第七章 采购需求偏离表', 类型: '填空区' },
        { id: 'chap.8', 标题: '第八章 历史同类业绩与团队人员', 类型: '自撰区' },
        { id: 'chap.9', 标题: '第九章 整体服务方案与质量控制', 类型: '自撰区' },
      ],
    },
  ],
  requirements: [
    { id: 'req.price', 文本: '投标报价不得超过最高限价', 标识: '★', 分值: 10 },
    { id: 'req.perf', 文本: '京津冀同类三甲医院计量检测业绩（每提供 1 个得 3 分，最高 10 分）', 分值: 10 },
    { id: 'req.cnas', 文本: '具有中国合格评定国家认可委员会（CNAS）认可证书', 分值: 5 },
    { id: 'req.need', 文本: '采购需求参数及条款响应，无负偏离', 分值: 22 },
    { id: 'req.plan', 文本: '整体检测服务方案（含方案、流程、报告质量控制）', 分值: 15 },
    { id: 'req.people', 文本: '拟任技术负责人须具备二级及以上注册计量师资格', 分值: 13 },
    { id: 'req.qc', 文本: '质量保障管理与检测设备溯源、校准证书完备性', 分值: 10 },
    { id: 'req.emg', 文本: '应急预案及突发故障处置机制', 分值: 10 },
    { id: 'req.send', 文本: '承诺协助强检及强检送检申报', 标识: '★' },
  ],
  mapping: [
    { id: 'map.cnas', requirementId: 'req.cnas', volumeId: 'vol.1', chapterId: 'chap.1', 证据类型: 'CNAS 证书' },
    { id: 'map.need', requirementId: 'req.need', volumeId: 'vol.1', chapterId: 'chap.7', 证据类型: '偏离表' },
    { id: 'map.perf', requirementId: 'req.perf', volumeId: 'vol.1', chapterId: 'chap.8', 证据类型: '业绩合同' },
    { id: 'map.people', requirementId: 'req.people', volumeId: 'vol.1', chapterId: 'chap.8', 证据类型: '注册计量师证' },
    { id: 'map.plan', requirementId: 'req.plan', volumeId: 'vol.1', chapterId: 'chap.9', 证据类型: '服务方案' },
  ],
  materials: [
    { id: 'mat.cnas', category: 'qual', 名称: 'CNAS 认可证书 (编号: L48532，含计量校准范围)', 命中: true },
    { id: 'mat.cma', category: 'qual', 名称: 'CMA 计量认证资质 + 认可能力附表', 命中: true },
    { id: 'mat.rad', category: 'qual', 名称: '放射卫生评价/检测机构资质 (乙级)', 命中: false },
    { id: 'mat.wjg', category: 'people', 名称: '吴建刚 · 一级注册计量师证 + 5 年社保证明', 命中: true },
    { id: 'mat.wwj', category: 'people', 名称: '武文君 · 二级注册计量师证 + 在保社保证明', 命中: true },
    { id: 'mat.perf-bj', category: 'record', 名称: '北京地区同类业绩 3 例 (305医院/北京武警总队/空军特色医学中心)', 命中: true, 口径警告: '招标要求「京津冀地区」，资料库命中为「北京」三甲业绩，口径置信度需人工决断确认' },
    { id: 'mat.tpl-plan', category: 'template', 名称: '医疗设备检测服务方案、质量控制、应急预案通用模板', 命中: true },
  ],
  blocks: [
    {
      id: 'blk.open',
      chapterId: 'chap.5',
      render: 'form',
      标题: '开标一览表 (投标函附录)',
      form: [
        { label: '投标总价 (大写)', value: '贰拾陆万玖仟捌佰贰拾元整' },
        { label: '投标总价 (小写)', value: '¥269,820.00' },
        { label: '预算利用率', value: '99.93%' },
        { label: '投标保证金', value: '¥5,400.00 (已从对公账户网银转账足额缴纳)' },
        { label: '服务期限', value: '自合同签订之日起 1 年' },
      ],
    },
    {
      id: 'blk.cnas',
      chapterId: 'chap.1',
      render: 'attachment',
      标题: 'CNAS 认可证书扫描件',
      attachment: { 名称: 'CNAS_Certificate_L48532_Signed.pdf', materialId: 'mat.cnas' },
    },
    {
      id: 'blk.dev',
      chapterId: 'chap.7',
      render: 'table',
      标题: '采购需求参数偏离表 (关键响应条款)',
      table: {
        headers: ['招标文件要求', '投标文件响应', '偏离方向/说明'],
        rows: [
          ['检测现场响应时间 ≤ 5 天', '我司承诺接到检测指令后 1 天内到达现场', '无偏离 (优于招标要求)'],
          ['投标人成立年限满 3 年以上', '我司成立于 2020 年，运营 5 年以上，财务稳健', '无偏离 (完全满足)'],
          ['★ 强检及送检协助义务', '出具《强检送检专项承诺函》，相关协办费用在报价表中报 0', '完全响应'],
        ],
      },
    },
    {
      id: 'blk.perf',
      chapterId: 'chap.8',
      render: 'table',
      标题: '近三年同类三甲医院计量检测业绩清单',
      table: {
        headers: ['序号', '项目名称', '合同签署方', '签约金额', '服务期'],
        rows: [
          ['1', '中国人民解放军总医院第五医学中心计量检测', '迈创精准', '¥86,400.00', '2024-2025'],
          ['2', '武警北京总队医院医用设备校准项目', '迈创精准', '¥115,000.00', '2023-2024'],
          ['3', '北京 305 医院设备溯源与周期校准', '迈创精准', '¥68,000.00', '2025'],
        ],
      },
    },
    {
      id: 'blk.people',
      chapterId: 'chap.8',
      render: 'attachment',
      标题: '技术负责人注册计量师证书 (武文君)',
      attachment: { 名称: '武文君_二级注册计量师_202203112.pdf', materialId: 'mat.wwj' },
    },
    {
      id: 'blk.plan',
      chapterId: 'chap.9',
      render: 'prose',
      标题: '整体计量检测服务方案 (质量保障控制体系节选)',
      prose: '我司依据 ISO 9001 质量管理体系与 CNAS 实验室认可准则，针对北京口腔医院建立专属质控闭环：现场响应时间缩短至 1 天（大幅优于 ≤5 天标准）；检测数据实施双人交互复核机制，全部流程通过数字化计量平台可直接追溯至国家计量基准；配备精密移液器校准器、黑体炉、数字多功能计量标准器等标准器 134 项。售后提供 8 小时极速出具检测报告服务及突发故障应急返工机制，全天候保障临床科室计量器具及大中型影像设备零积压、零停摆。',
    },
  ],
  redlines: [
    { id: 'rl.price', 项: '投标报价低于或等于最高限价', 结果: 'pass', 说明: '报价 269,820 元 ≤ 限价 270,000 元 (符合)' },
    { id: 'rl.index', 项: '四张索引表与偏离表逐条应答无空白', 结果: 'pass', 说明: '已完整填写索引表及商务技术偏离表' },
    { id: 'rl.copy', 项: '技术条款响应改写，未原文照抄招标文件', 结果: 'pass', 说明: '针对 12 项技术参数实施个性化响应改写 (避雷照抄判定)' },
    { id: 'rl.star', 项: '★ 实质性核心条款多重应答及兜底', 结果: 'pass', 说明: '针对 ★ 强检及协助条款在偏离表与承诺函中进行了双重保障' },
    { id: 'rl.split', 项: '分项报价表单独填报且价格勾稽一致', 结果: 'pass', 说明: '分项报价加总为 269,820 元，与开标一览表完全一致' },
  ],
  pricing: {
    lines: [
      { 项目: '精密移液器校准 (单价 120, 包含 10、20、50、100ul 常用规格)', 数量: 200, 单价: 120, 小计: 24000 },
      { 项目: '医用高频电刀专项校准与安全检测', 数量: 35, 单价: 800, 小计: 28000 },
      { 项目: '多参数监护仪、脉搏血氧仪校准与溯源', 数量: 180, 单价: 300, 小计: 54000 },
      { 项目: '放射类及牙科 X 射线设备计量检测与辐射安全防护评价', 数量: 12, 单价: 8000, 小计: 96000 },
      { 项目: '高压蒸汽灭菌器、医用离心机等物理检测服务', 数量: 62, 单价: 1093.87, 小计: 67820 },
    ],
    限价: 270000,
    报价: 269820,
    利用率: '99.93%',
  },
  steps: [
    { id: 'k1', stage: 1, kind: 'log', duration: 1000, log: '解析遴选招标文件：提取 27 项技术指标 · 8 条 ★ 实质性红线 · 判定为综合评分法' },
    { id: 'k2', stage: 2, kind: 'checkpoint', duration: 0, checkpointTitle: '确认投标编写策略', checkpointBody: '综合评分法下价格权重仅 10%，技术和业绩占 90%。AI 建议：高精度顶格报价（269,820 元，利用率 99.93%），资源全面倾斜于「技术方案高还原度」与「专家加分项」以赢取 90 分技术分池。' },
    { id: 'k3', stage: 3, kind: 'growTree', duration: 800, treeVolumeId: 'vol.1', log: '根据招标文件指引：自主搭建单分册《投标文件》大纲结构（第 1–9 章）' },
    { id: 'k4', stage: 4, kind: 'log', duration: 800, log: '需求与章节逆向镜像映射：将 9 项核心评审要素一一映射至册、章节及相应证据链' },
    { id: 'k5', stage: 5, kind: 'matchMaterial', duration: 900, log: '库检索命中：CNAS 认可证书 (编号 L48532) 满足「实验室国家认可」5 分项 ✅', focus: { material: 'mat.cnas', drawer: 'qual', mapRow: 'map.cnas', docBlock: 'blk.cnas', chapter: 'chap.1' } },
    { id: 'k6', stage: 6, kind: 'genBlock', duration: 900, blockId: 'blk.cnas', focus: { docBlock: 'blk.cnas', chapter: 'chap.1' } },
    {
      id: 'k7',
      stage: 5,
      kind: 'escalate',
      duration: 0,
      escalateTitle: '业绩条款口径匹配警告 (🔴 升级决断)',
      escalateBody: '招标评审表要求「京津冀地区三甲医院同类业绩」。当前公司资料库匹配度最高为北京三甲业绩 3 例，缺失天津/河北的签约原件。若直接提报，在综合评分中可能有专家主观扣 1-2 分风险。是否自动追加外部联合渠道的天津/河北补充业绩？',
      confidence: 0.62,
      options: [
        {
          label: '自动补充联合体津冀业绩 (推荐，得满分)',
          effect: {
            type: 'insert',
            steps: [
              { id: 'k7.sub1', stage: 5, kind: 'log', duration: 800, log: '向外部可信网络发起 RAG 检测… 命中补充协议：提供天津市医科大学总医院与河北省第二医院业绩证明 ✅' },
            ],
          },
        },
        { label: '维持北京三甲业绩申报 (稳健，保留轻微扣分项)', effect: { type: 'continue' } },
      ],
    },
    { id: 'k8', stage: 6, kind: 'genBlock', duration: 1000, blockId: 'blk.perf', focus: { docBlock: 'blk.perf', chapter: 'chap.8' } },
    { id: 'k9', stage: 5, kind: 'matchMaterial', duration: 800, log: '库检索命中拟任技术负责人：武文君 · 二级注册计量师证 ✅', focus: { material: 'mat.wwj', drawer: 'people', mapRow: 'map.people', docBlock: 'blk.people' } },
    {
      id: 'k_supp_social',
      stage: 5,
      kind: 'supplement',
      duration: 0,
      supplementType: 'social',
      supplementTitle: '★ 缺失核心资质：拟派项目团队在册社保证明',
      supplementBody: '招标文件第 8 章明确要求：拟任所有项目组成员均须提供近 3 个月连续足额缴纳对公社保证明，严禁挂靠及社保代缴。Agent 在本地历史企业底册中未检索到武文君的最新的参保证明，为避免废标红线扣分，请人工补齐。',
    },
    { id: 'k10', stage: 6, kind: 'genBlock', duration: 900, blockId: 'blk.people', focus: { docBlock: 'blk.people', chapter: 'chap.8' } },
    { id: 'k11', stage: 6, kind: 'genBlock', duration: 1100, blockId: 'blk.dev', focus: { docBlock: 'blk.dev', chapter: 'chap.7' } },
    { id: 'k12', stage: 6, kind: 'genBlock', duration: 1500, blockId: 'blk.plan', focus: { docBlock: 'blk.plan', chapter: 'chap.9' } },
    { id: 'k13', stage: 6, kind: 'genBlock', duration: 800, blockId: 'blk.open', focus: { docBlock: 'blk.open', chapter: 'chap.5' } },
    {
      id: 'k_supp_tax',
      stage: 5,
      kind: 'supplement',
      duration: 0,
      supplementType: 'tax',
      supplementTitle: '⚠️ 缺失合规佐证：企业近半年依法纳税电子缴存凭证',
      supplementBody: '第二章《资格声明书》合规性审查需要提供海淀区税务局开具的电子完税缴纳回执。Agent 在本地资料库及近期标书中未发现对应的电子凭证，请一键提供纳税截图以供多模态高精度提取和防伪对账。',
    },
    {
      id: 'k_supp_pricing',
      stage: 7,
      kind: 'supplement',
      duration: 0,
      supplementType: 'pricing',
      supplementTitle: '⚠️ 缺失关键文件：分项报价精算与对标估算试算底单',
      supplementBody: '分项报价加总必须与投标函大写金额绝对钩稽（无 0.01 元尾差）。Agent 需要对标您线下计算的分项精算底单，以精确调校第六章中的分项报价数额。请人工一键补充。',
    },
    { id: 'k14', stage: 7, kind: 'pricing', duration: 900, pricingReveal: true, log: '价格分析引擎运行：顶格测算 269,820 元，分项总和与投标函大写金额绝对钩稽，限价空间利用率 99.93%' },
    { id: 'k15', stage: 8, kind: 'redlineResult', duration: 400, redlineId: 'rl.price' },
    { id: 'k16', stage: 8, kind: 'redlineResult', duration: 400, redlineId: 'rl.index' },
    { id: 'k17', stage: 8, kind: 'redlineResult', duration: 400, redlineId: 'rl.copy' },
    { id: 'k18', stage: 8, kind: 'redlineResult', duration: 400, redlineId: 'rl.star' },
    { id: 'k19', stage: 8, kind: 'redlineResult', duration: 400, redlineId: 'rl.split' },
    { id: 'k20', stage: 9, kind: 'export', duration: 0, checkpointTitle: '全册内容多维自检通过 · 准备按规范打包导出' },
  ],
};
